version: "3.6"
services:
  kong:
    image: kong:2.2.0-alpine
    volumes:
      - /data/kong:/usr/local/kong/declarative
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "80:8000"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    networks:
      - kong-net
  # openresty:
  #   image: openresty/openresty:1.19.3.1-0-alpine
  #   volumes:
  #     - /data/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  #     - /data/openresty/lua:/usr/local/openresty/lua
  #   ports:
  #     - "80:80"
  #   networks:
  #     - kong-net
  ssooidcapi:
    image: syrianazh/sso.oidc.api:0.0.1-SNAPSHOT
    networks:
      - kong-net
  ssooidcsrv:
    image: syrianazh/sso.oidc.srv:0.0.2-SNAPSHOT
    networks:
      - kong-net
networks:
  kong-net:
    external: true
    name: kong-net